services:
  backend:
    build:
      context: ./Tejvanta.Api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./tejvanta-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
