-- Tejvanta Database Schema (PostgreSQL)
-- Run this script to initialize the database

CREATE TABLE IF NOT EXISTS "Instruments" (
    "Id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "Symbol" VARCHAR(50) NOT NULL,
    "Name" VARCHAR(200) NOT NULL,
    "Exchange" VARCHAR(20) NOT NULL DEFAULT 'NSE',
    "TickSize" NUMERIC(10,2) NOT NULL DEFAULT 0.05,
    "LotSize" INTEGER NOT NULL DEFAULT 1,
    "Segment" VARCHAR(20) NOT NULL DEFAULT 'EQ',
    "Series" VARCHAR(10) NOT NULL DEFAULT 'EQ',
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "IX_Instruments_Symbol" ON "Instruments" ("Symbol");

CREATE TABLE IF NOT EXISTS "Candles" (
    "Id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "InstrumentId" INTEGER NOT NULL REFERENCES "Instruments"("Id"),
    "Timestamp" TIMESTAMP NOT NULL,
    "Open" NUMERIC(14,2) NOT NULL,
    "High" NUMERIC(14,2) NOT NULL,
    "Low" NUMERIC(14,2) NOT NULL,
    "Close" NUMERIC(14,2) NOT NULL,
    "Volume" BIGINT NOT NULL,
    "Timeframe" VARCHAR(10) NOT NULL DEFAULT '1m'
);

CREATE INDEX IF NOT EXISTS "IX_Candles_InstrumentId_Timestamp" ON "Candles" ("InstrumentId", "Timestamp", "Timeframe");

CREATE TABLE IF NOT EXISTS "Ticks" (
    "Id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "InstrumentId" INTEGER NOT NULL REFERENCES "Instruments"("Id"),
    "Timestamp" TIMESTAMP NOT NULL,
    "Price" NUMERIC(14,2) NOT NULL,
    "Volume" BIGINT NOT NULL,
    "Bid" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "Ask" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "Open" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "High" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "Low" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "PrevClose" NUMERIC(14,2) NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS "IX_Ticks_InstrumentId_Timestamp" ON "Ticks" ("InstrumentId", "Timestamp");

CREATE TABLE IF NOT EXISTS "PaperOrders" (
    "Id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "UserId" INTEGER NOT NULL DEFAULT 1,
    "InstrumentId" INTEGER NOT NULL REFERENCES "Instruments"("Id"),
    "Side" VARCHAR(10) NOT NULL,
    "OrderType" VARCHAR(20) NOT NULL,
    "Price" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "Quantity" INTEGER NOT NULL,
    "StopLoss" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "TakeProfit" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "Status" VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    "RejectionReason" VARCHAR(500),
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMP,
    "FilledQuantity" INTEGER NOT NULL DEFAULT 0,
    "AvgFillPrice" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "BasketId" VARCHAR(50)
);

CREATE INDEX IF NOT EXISTS "IX_PaperOrders_UserId_Status" ON "PaperOrders" ("UserId", "Status");

CREATE TABLE IF NOT EXISTS "PaperTrades" (
    "Id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" INTEGER NOT NULL REFERENCES "PaperOrders"("Id"),
    "InstrumentId" INTEGER NOT NULL REFERENCES "Instruments"("Id"),
    "Price" NUMERIC(14,2) NOT NULL,
    "Quantity" INTEGER NOT NULL,
    "Side" VARCHAR(10) NOT NULL,
    "TradeTime" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "PaperPositions" (
    "Id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "UserId" INTEGER NOT NULL DEFAULT 1,
    "InstrumentId" INTEGER NOT NULL REFERENCES "Instruments"("Id"),
    "Quantity" INTEGER NOT NULL DEFAULT 0,
    "AvgPrice" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "RealizedPnL" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "UnrealizedPnL" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "CurrentPrice" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "UQ_PaperPositions_User_Instrument" UNIQUE ("UserId", "InstrumentId")
);

CREATE TABLE IF NOT EXISTS "OptionsContracts" (
    "Id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "UnderlyingInstrumentId" INTEGER NOT NULL REFERENCES "Instruments"("Id"),
    "Strike" NUMERIC(14,2) NOT NULL,
    "Expiry" DATE NOT NULL,
    "OptionType" VARCHAR(5) NOT NULL,
    "LTP" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "Bid" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "Ask" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "OpenInterest" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "Volume" BIGINT NOT NULL DEFAULT 0,
    "IV" NUMERIC(5,2) NOT NULL DEFAULT 0,
    "Change" NUMERIC(14,2) NOT NULL DEFAULT 0,
    "ChangePercent" NUMERIC(8,2) NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS "IX_OptionsContracts_Underlying_Expiry" ON "OptionsContracts" ("UnderlyingInstrumentId", "Expiry", "Strike", "OptionType");

CREATE TABLE IF NOT EXISTS "UserSettings" (
    "Id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "UserId" INTEGER NOT NULL UNIQUE DEFAULT 1,
    "Theme" VARCHAR(20) NOT NULL DEFAULT 'dark',
    "DefaultTimeframe" VARCHAR(10) NOT NULL DEFAULT '1D',
    "DefaultLayout" INTEGER NOT NULL DEFAULT 1,
    "Timezone" VARCHAR(50) NOT NULL DEFAULT 'Asia/Kolkata',
    "VirtualBalance" NUMERIC(16,2) NOT NULL DEFAULT 1000000,
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "Layouts" (
    "Id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "UserId" INTEGER NOT NULL DEFAULT 1,
    "Name" VARCHAR(100) NOT NULL DEFAULT 'Default',
    "ConfigJson" TEXT NOT NULL DEFAULT '{}',
    "IsDefault" BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "Watchlists" (
    "Id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "UserId" INTEGER NOT NULL DEFAULT 1,
    "Name" VARCHAR(100) NOT NULL DEFAULT 'Default',
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "WatchlistItems" (
    "Id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "WatchlistId" INTEGER NOT NULL REFERENCES "Watchlists"("Id"),
    "InstrumentId" INTEGER NOT NULL REFERENCES "Instruments"("Id"),
    "SortOrder" INTEGER NOT NULL DEFAULT 0
);

-- Default user settings
INSERT INTO "UserSettings" ("UserId", "Theme", "DefaultTimeframe", "DefaultLayout", "Timezone", "VirtualBalance")
VALUES (1, 'dark', '1D', 1, 'Asia/Kolkata', 1000000)
ON CONFLICT ("UserId") DO NOTHING;

-- Default watchlist
INSERT INTO "Watchlists" ("UserId", "Name") VALUES (1, 'Default')
ON CONFLICT DO NOTHING;
